[2023-06-29 18:49:09,589: INFO: main: >>>> Stage Data Ingestion Stage started <<<<]
[2023-06-29 18:49:09,589: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 18:49:09,590: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 18:49:09,590: INFO: common: Directory artifacts created successfully]
[2023-06-29 18:49:09,590: INFO: common: Directory artifacts/data_ingestion created successfully]
[2023-06-29 18:51:49,057: INFO: dataIngestion: artifacts/data_ingestion/data.zip download! with following info: 
Server: nginx/1.14.0 (Ubuntu)
Date: Thu, 29 Jun 2023 07:49:09 GMT
Content-Type: application/zip
Content-Length: 40854701
Last-Modified: Thu, 17 Sep 2020 05:05:40 GMT
Connection: close
ETag: "5f62eea4-26f64ad"
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Accept-Ranges: bytes

]
[2023-06-29 18:51:49,907: INFO: main: >>>> Stage Data Ingestion Stage completed <<<<

X=============================X]
[2023-06-29 19:56:22,316: INFO: main: >>>> Stage Data Format Stage started <<<<]
[2023-06-29 19:56:22,317: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 19:56:22,317: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 19:56:22,317: INFO: common: Directory artifacts created successfully]
[2023-06-29 19:56:22,318: ERROR: main: 'NoneType' object has no attribute 'datafile']
Traceback (most recent call last):
  File "/home/shaw/Documents/Projects/Chatbot/main.py", line 19, in <module>
    data_format.main()
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/pipeline/stage02_dataFormat.py", line 23, in main
    lines, conversations = data_format.loadLinesAndConversations()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataFormat.py", line 13, in loadLinesAndConversations
    with open(self.config.datafile, 'r', encoding='iso-8859-1') as f:
              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'datafile'
[2023-06-29 19:58:24,271: INFO: main: >>>> Stage Data Format Stage started <<<<]
[2023-06-29 19:58:24,271: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 19:58:24,272: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 19:58:24,272: INFO: common: Directory artifacts created successfully]
[2023-06-29 19:58:24,272: ERROR: main: 'NoneType' object has no attribute 'utterances']
Traceback (most recent call last):
  File "/home/shaw/Documents/Projects/Chatbot/main.py", line 19, in <module>
    data_format.main()
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/pipeline/stage02_dataFormat.py", line 23, in main
    lines, conversations = data_format.loadLinesAndConversations(data_format_config.utterances)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'utterances'
[2023-06-29 20:04:27,223: INFO: main: >>>> Stage Data Format Stage started <<<<]
[2023-06-29 20:04:27,224: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 20:04:27,224: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 20:04:27,224: INFO: common: Directory artifacts created successfully]
[2023-06-29 20:04:27,224: ERROR: main: 'NoneType' object has no attribute 'utterances']
Traceback (most recent call last):
  File "/home/shaw/Documents/Projects/Chatbot/main.py", line 19, in <module>
    data_format.main()
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/pipeline/stage02_dataFormat.py", line 23, in main
    lines, conversations = data_format.loadLinesAndConversations(data_format_config.utterances)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'utterances'
[2023-06-29 20:05:50,402: INFO: main: >>>> Stage Data Format Stage started <<<<]
[2023-06-29 20:05:50,403: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 20:05:50,404: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 20:05:50,404: INFO: common: Directory artifacts created successfully]
[2023-06-29 20:05:50,404: ERROR: main: DataFormat.loadLinesAndConversations() takes 1 positional argument but 2 were given]
Traceback (most recent call last):
  File "/home/shaw/Documents/Projects/Chatbot/main.py", line 19, in <module>
    data_format.main()
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/pipeline/stage02_dataFormat.py", line 23, in main
    lines, conversations = data_format.loadLinesAndConversations(data_format_config.utterances)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataFormat.loadLinesAndConversations() takes 1 positional argument but 2 were given
[2023-06-29 20:06:48,378: INFO: main: >>>> Stage Data Format Stage started <<<<]
[2023-06-29 20:06:48,379: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 20:06:48,380: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 20:06:48,380: INFO: common: Directory artifacts created successfully]
[2023-06-29 20:06:48,380: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/movie-corpus/formatted_movie_lines.txt']
Traceback (most recent call last):
  File "/home/shaw/Documents/Projects/Chatbot/main.py", line 19, in <module>
    data_format.main()
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/pipeline/stage02_dataFormat.py", line 23, in main
    lines, conversations = data_format.loadLinesAndConversations()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataFormat.py", line 13, in loadLinesAndConversations
    with open(self.config.datafile, 'r', encoding='iso-8859-1') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/movie-corpus/formatted_movie_lines.txt'
[2023-06-29 20:07:29,330: INFO: main: >>>> Stage Data Format Stage started <<<<]
[2023-06-29 20:07:29,331: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 20:07:29,331: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 20:07:29,332: INFO: common: Directory artifacts created successfully]
[2023-06-29 20:07:33,354: INFO: dataFormat: Loaded Lines and Coversations successfully!]
[2023-06-29 20:07:33,354: ERROR: main: DataFormat.extractSentencePairs() takes 1 positional argument but 2 were given]
Traceback (most recent call last):
  File "/home/shaw/Documents/Projects/Chatbot/main.py", line 19, in <module>
    data_format.main()
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/pipeline/stage02_dataFormat.py", line 28, in main
    for pair in data_format.extractSentencePairs(conversations):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DataFormat.extractSentencePairs() takes 1 positional argument but 2 were given
[2023-06-29 20:09:08,078: INFO: main: >>>> Stage Data Format Stage started <<<<]
[2023-06-29 20:09:08,079: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 20:09:08,080: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 20:09:08,080: INFO: common: Directory artifacts created successfully]
[2023-06-29 20:09:12,147: INFO: dataFormat: Loaded Lines and Coversations successfully!]
[2023-06-29 20:09:12,505: INFO: dataFormat: Extracted Sentence Pairs]
[2023-06-29 20:09:12,889: INFO: main: >>>> Stage Data Format Stage completed <<<<

X=============================X]
[2023-06-29 22:47:02,429: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 22:47:02,429: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 22:47:02,430: INFO: common: Directory artifacts created successfully]
[2023-06-29 22:47:02,430: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 22:51:47,411: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 22:51:47,411: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 22:51:47,412: INFO: common: Directory artifacts created successfully]
[2023-06-29 22:51:47,412: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 22:55:16,139: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 22:55:16,140: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 22:55:16,140: INFO: common: Directory artifacts created successfully]
[2023-06-29 22:55:16,140: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 22:55:16,141: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 22:55:16,141: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 22:55:16,141: INFO: common: Directory artifacts created successfully]
[2023-06-29 22:55:16,141: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 22:55:16,141: INFO: main: >>>> Stage Data Load Stage started <<<<]
[2023-06-29 22:55:16,182: ERROR: main: name 'unicodedata' is not defined]
Traceback (most recent call last):
  File "/home/shaw/Documents/Projects/Chatbot/main.py", line 30, in <module>
    voc, pairs = data_load.main()
                 ^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/pipeline/stage03_dataLoad.py", line 13, in main
    voc, pairs = loadPrepareData(config.corpus, config.corpus_name, config.datafile, config.save_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataLoad.py", line 102, in loadPrepareData
    voc, pairs = readVocs(datafile, corpus_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataLoad.py", line 86, in readVocs
    pairs = [[normalizeString(s) for s in l.split('\t')] for l in lines]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataLoad.py", line 86, in <listcomp>
    pairs = [[normalizeString(s) for s in l.split('\t')] for l in lines]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataLoad.py", line 86, in <listcomp>
    pairs = [[normalizeString(s) for s in l.split('\t')] for l in lines]
              ^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataLoad.py", line 73, in normalizeString
    s = unicodeToAscii(s.lower().strip())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataLoad.py", line 67, in unicodeToAscii
    c for c in unicodedata.normalize('NFD', s)
               ^^^^^^^^^^^
NameError: name 'unicodedata' is not defined
[2023-06-29 22:56:48,087: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 22:56:48,087: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 22:56:48,087: INFO: common: Directory artifacts created successfully]
[2023-06-29 22:56:48,087: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 22:56:48,089: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 22:56:48,089: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 22:56:48,089: INFO: common: Directory artifacts created successfully]
[2023-06-29 22:56:48,089: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 22:56:48,090: INFO: main: >>>> Stage Data Load Stage started <<<<]
[2023-06-29 22:56:53,484: ERROR: main: name 'PAD_token' is not defined]
Traceback (most recent call last):
  File "/home/shaw/Documents/Projects/Chatbot/main.py", line 30, in <module>
    voc, pairs = data_load.main()
                 ^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/pipeline/stage03_dataLoad.py", line 13, in main
    voc, pairs = loadPrepareData(config.corpus, config.corpus_name, config.datafile, config.save_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataLoad.py", line 103, in loadPrepareData
    voc, pairs = readVocs(datafile, corpus_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataLoad.py", line 88, in readVocs
    voc = Voc(corpus_name)
          ^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataLoad.py", line 19, in __init__
    self.index2word = {PAD_token: "PAD", SOS_token: "SOS", EOS_token: "EOS"}
                       ^^^^^^^^^
NameError: name 'PAD_token' is not defined
[2023-06-29 22:57:28,443: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 22:57:28,444: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 22:57:28,444: INFO: common: Directory artifacts created successfully]
[2023-06-29 22:57:28,444: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 22:57:28,445: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 22:57:28,445: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 22:57:28,445: INFO: common: Directory artifacts created successfully]
[2023-06-29 22:57:28,445: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 22:57:28,446: INFO: main: >>>> Stage Data Load Stage started <<<<]
[2023-06-29 22:57:34,076: INFO: main: >>>> Stage Data Load Stage completed <<<<

X=============================X]
[2023-06-29 23:24:22,742: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 23:24:22,743: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 23:24:22,743: INFO: common: Directory artifacts created successfully]
[2023-06-29 23:24:22,743: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 23:24:22,744: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 23:24:22,744: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 23:24:22,744: INFO: common: Directory artifacts created successfully]
[2023-06-29 23:24:22,744: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 23:25:08,150: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 23:25:08,151: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 23:25:08,151: INFO: common: Directory artifacts created successfully]
[2023-06-29 23:25:08,151: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 23:25:08,152: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 23:25:08,153: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 23:25:08,153: INFO: common: Directory artifacts created successfully]
[2023-06-29 23:25:08,153: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 23:25:08,155: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 23:25:08,155: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 23:25:08,156: INFO: common: Directory artifacts created successfully]
[2023-06-29 23:25:08,156: INFO: main: >>>> Stage Data Load Stage started <<<<]
[2023-06-29 23:25:13,884: INFO: main: >>>> Stage Data Load Stage completed <<<<

X=============================X]
[2023-06-29 23:25:13,884: INFO: main: >>>> Stage Data Prepare Stage started <<<<]
[2023-06-29 23:25:13,884: ERROR: main: name 'random' is not defined]
Traceback (most recent call last):
  File "/home/shaw/Documents/Projects/Chatbot/main.py", line 41, in <module>
    input_variable, lengths, target_variable, mask, max_target_len = data_prepare.main()
                                                                     ^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/pipeline/stage04_dataPrepare.py", line 14, in main
    input_variable, lengths, target_variable, mask, max_target_len = batch2TrainData(self.voc, [random.choice(self.pairs) for _ in range(small_batch_size)])
                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/pipeline/stage04_dataPrepare.py", line 14, in <listcomp>
    input_variable, lengths, target_variable, mask, max_target_len = batch2TrainData(self.voc, [random.choice(self.pairs) for _ in range(small_batch_size)])
                                                                                                ^^^^^^
NameError: name 'random' is not defined
[2023-06-29 23:25:34,228: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 23:25:34,229: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 23:25:34,229: INFO: common: Directory artifacts created successfully]
[2023-06-29 23:25:34,229: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 23:25:34,230: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 23:25:34,230: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 23:25:34,230: INFO: common: Directory artifacts created successfully]
[2023-06-29 23:25:34,230: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 23:25:34,232: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 23:25:34,232: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 23:25:34,232: INFO: common: Directory artifacts created successfully]
[2023-06-29 23:25:34,232: INFO: main: >>>> Stage Data Load Stage started <<<<]
[2023-06-29 23:25:39,977: INFO: main: >>>> Stage Data Load Stage completed <<<<

X=============================X]
[2023-06-29 23:25:39,978: INFO: main: >>>> Stage Data Prepare Stage started <<<<]
[2023-06-29 23:25:39,978: ERROR: main: name 'torch' is not defined]
Traceback (most recent call last):
  File "/home/shaw/Documents/Projects/Chatbot/main.py", line 41, in <module>
    input_variable, lengths, target_variable, mask, max_target_len = data_prepare.main()
                                                                     ^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/pipeline/stage04_dataPrepare.py", line 15, in main
    input_variable, lengths, target_variable, mask, max_target_len = batch2TrainData(self.voc, [random.choice(self.pairs) for _ in range(small_batch_size)])
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataPrepare.py", line 46, in batch2TrainData
    inp, lengths = inputVar(input_batch, voc)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataPrepare.py", line 24, in inputVar
    lengths = torch.tensor([len(indexes) for indexes in indexes_batch])
              ^^^^^
NameError: name 'torch' is not defined
[2023-06-29 23:26:02,532: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 23:26:02,533: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 23:26:02,533: INFO: common: Directory artifacts created successfully]
[2023-06-29 23:26:02,533: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 23:26:02,534: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 23:26:02,534: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 23:26:02,535: INFO: common: Directory artifacts created successfully]
[2023-06-29 23:26:02,535: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 23:26:03,260: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 23:26:03,261: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 23:26:03,261: INFO: common: Directory artifacts created successfully]
[2023-06-29 23:26:03,261: INFO: main: >>>> Stage Data Load Stage started <<<<]
[2023-06-29 23:26:09,270: INFO: main: >>>> Stage Data Load Stage completed <<<<

X=============================X]
[2023-06-29 23:26:09,270: INFO: main: >>>> Stage Data Prepare Stage started <<<<]
[2023-06-29 23:26:09,271: ERROR: main: name 'itertools' is not defined]
Traceback (most recent call last):
  File "/home/shaw/Documents/Projects/Chatbot/main.py", line 41, in <module>
    input_variable, lengths, target_variable, mask, max_target_len = data_prepare.main()
                                                                     ^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/pipeline/stage04_dataPrepare.py", line 15, in main
    input_variable, lengths, target_variable, mask, max_target_len = batch2TrainData(self.voc, [random.choice(self.pairs) for _ in range(small_batch_size)])
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataPrepare.py", line 47, in batch2TrainData
    inp, lengths = inputVar(input_batch, voc)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataPrepare.py", line 26, in inputVar
    padList = zeroPadding(indexes_batch)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaw/Documents/Projects/Chatbot/src/ChatBot/components/dataPrepare.py", line 9, in zeroPadding
    return list(itertools.zip_longest(*l, fillvalue=fillvalue))
                ^^^^^^^^^
NameError: name 'itertools' is not defined
[2023-06-29 23:26:23,407: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 23:26:23,408: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 23:26:23,408: INFO: common: Directory artifacts created successfully]
[2023-06-29 23:26:23,408: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 23:26:23,409: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 23:26:23,409: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 23:26:23,409: INFO: common: Directory artifacts created successfully]
[2023-06-29 23:26:23,409: INFO: common: Directory artifacts/save created successfully]
[2023-06-29 23:26:24,132: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-06-29 23:26:24,132: INFO: common: yaml file: params.yaml loaded successfully]
[2023-06-29 23:26:24,132: INFO: common: Directory artifacts created successfully]
[2023-06-29 23:26:24,132: INFO: main: >>>> Stage Data Load Stage started <<<<]
[2023-06-29 23:26:30,204: INFO: main: >>>> Stage Data Load Stage completed <<<<

X=============================X]
[2023-06-29 23:26:30,204: INFO: main: >>>> Stage Data Prepare Stage started <<<<]
[2023-06-29 23:26:30,205: INFO: main: >>>> Stage Data Prepare Stage completed <<<<

X=============================X]
